### ISSUE TITLE
graph not showing

### ISSUE THREAD

**Issue by kevinohashi** [kevinohashi/WPPerformanceTester#1]
I've heard a couple reports of the graph not loading on some WP installs. I haven't been able to reproduce this phenomena. If you have this happen, could you please check the console for javascript errors and share any details here?

Other helpful info might be what other plugins you have active at that time and what theme it is running.

Thanks!

**Comment by kevinohashi** [comment]
may have been HTTP/HTTPS issue, not sure if there are other causes of this problem. Leaving it open. HTTP/HTTPS was solved with https://github.com/kevinohashi/WPPerformanceTester/commit/0dc886f22b01340ed1d22a572ba78e5f96aabc56

**Comment by timmarchant** [comment]
Kevin

I am having the same problem on installs on one of my servers - tests run fine on my other servers, but not on this one. Page is just blank, https is not an issue. Getting:

Fatal error: Call to undefined function mysqli_connect() in /****/********/public_html/wp-content/plugins/WPPerformanceTester-master/benchmark.php on line 130

**Comment by kevinohashi** [comment]
I'm not sure how that's possible honestly. mysqli_connect is a native PHP function http://php.net/manual/en/function.mysqli-connect.php

what version of PHP are you running?

**Comment by timmarchant** [comment]
Hi, I have upgraded now, but it was (I think) 5.2. I think the option to enable this was missed at some point in the distant past and it just never got enabled, since the server runs very sweetly, there was no reason for anyone to check. I think it is likely that the other reports you have had have the same cause.

**Comment by kevinohashi** [comment]
So it works post-upgrade? I will leave this issue open because I'm not convinced it's the only reason (I've already found at least one other cause).

**Comment by timmarchant** [comment]
Kevin, works fine now, but you are right, there may well be other reasons. Great tool by the way, thanks.

**Comment by wrrr** [comment]
I have a separate webserver running mariadb over a private IP/LAN in the datacenter. MariaDB would not be the issue as it's a drop-in replacement for mysql. The test runs for about 5 seconds and returns back to the same state it started in.

PHP Version - 5.5.9-1ubuntu4.12
MySQL Version - 10.0.21-MariaDB-1~trusty

nginx error log

2015/10/03 20:14:48 [error] 49913#0: *171 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function mysqli_connect() in /srv/0025/wp-content/plugins/WPPerformanceTester-master/benchmark.php on line 130" while reading response header from upstream, client: 98.143.74.136, server: mydomain.com, request: "POST /wp-admin/tools.php?page=WPPerformanceTester_PluginSettings HTTP/1.1", upstream: "fastcgi://unix:/var/run/ajenti-v-php-fcgi-canadianmatchmakers-php-fcgi-0.sock:", host: "mydomain.com", referrer: "https://mydomain.com/wp-admin/tools.php?page=WPPerformanceTester_PluginSettings"

**Comment by kevinohashi** [comment]
@wrrr does this fix it? http://www.queryadmin.com/195/fastcgi-stderr-php-fatal-error-undefined-mysql_connect/

That error seems like mysqli isn't installed

**Comment by wrrr** [comment]
Yes, had to uncomment extension=mysqli.so in mods-available (Ubuntu 14.04)

thanks kevin!
stu
