### ISSUE TITLE
omit port number?

### ISSUE THREAD

**Issue by ahkok** [kevinohashi/WPPerformanceTester#6]
It seems HHVM doesn't like the port number at the end of the line, and crashes with "port number is not numeric".

https://github.com/kevinohashi/WPPerformanceTester/blob/master/benchmark.php#L130

I have hhvm and php setup with a local socket only, which couid contribute to this problem. Removing the port number argument from this line makes the test succesfully execute on both php7 and hhvm against a socket interface.

**Comment by kevinohashi** [comment]
Sorry to hear about the troubles. Trying to think of a good way to handle detecting and using that. Because some people might need port and some might not. Any ideas?

**Comment by ahkok** [comment]
I think you can find out from the php settings whether by default mysqli uses a socket file:

`mysqli.default_socket` - http://php.net/manual/en/mysqli.quickstart.connections.php

Of course, you could always try both (e.g. socket file first, then port)

**Comment by kevinohashi** [comment]
Forgot to update this but socket detection was added a while ago, hope that fixes it.
